import React, { useState } from 'react';
import { Fix, FixExecutionResult } from '../../types';

/**
 * Fix approval card: plain-English summary, collapsible code block,
 * restore-point checkbox, risk indicator, Approve / Deny / Ask for Details.
 */

interface Props {
  fix: Fix;
  result?: FixExecutionResult;
  onExecuted: (result: FixExecutionResult) => void;
}

const RISK_LABELS: Record<Fix['riskLevel'], string> = {
  low: 'Low risk',
  medium: 'Medium risk',
  high: 'High risk',
};

export default function FixApprovalModal({
  fix,
  result,
  onExecuted,
}: Props): JSX.Element {
  const [codeExpanded, setCodeExpanded] = useState(false);
  const [restorePoint, setRestorePoint] = useState(
    fix.riskLevel !== 'low' || fix.critical
  );
  const [denied, setDenied] = useState(false);
  const [running, setRunning] = useState(false);
  const [showDetails, setShowDetails] = useState(false);
  const [outputExpanded, setOutputExpanded] = useState(false);

  const approve = async () => {
    setRunning(true);
    try {
      const executionResult = await window.api.fixes.execute({
        fix,
        createRestorePoint: restorePoint,
      });
      onExecuted(executionResult);
    } finally {
      setRunning(false);
    }
  };

  const openRestore = () => {
    void window.api.fixes.openSystemRestore();
  };

  if (denied) {
    return (
      <div className="fix-card denied">
        <div className="fix-header">
          <span className="fix-title">{fix.title}</span>
          <span className="fix-status muted">Denied — no changes made</span>
        </div>
      </div>
    );
  }

  return (
    <div className={`fix-card ${result ? (result.status === 'Success' ? 'succeeded' : 'failed') : ''}`}>
      <div className="fix-header">
        <span className="fix-title">{fix.title}</span>
        <span className={`risk-badge risk-${fix.riskLevel}`}>
          {RISK_LABELS[fix.riskLevel]}
        </span>
        {fix.critical && <span className="risk-badge critical">UAC prompt</span>}
      </div>

      <p className="fix-description">{fix.description}</p>

      {showDetails && (
        <div className="fix-details">
          <p>
            <b>Category:</b> {fix.category} · <b>Shell:</b>{' '}
            {fix.shell === 'powershell' ? 'PowerShell' : 'Command Prompt'} ·{' '}
            <b>Elevation:</b>{' '}
            {fix.critical
              ? 'Shows a separate Windows UAC confirmation before running'
              : 'Runs in the app’s existing admin session'}
          </p>
          <p>
            This script was generated by AI and passed the app’s safety
            validator. Review the code below before approving. If you create a
            restore point, you can undo system-level changes later via System
            Restore.
          </p>
        </div>
      )}

      <button
        className="btn ghost sm code-toggle"
        onClick={() => setCodeExpanded((e) => !e)}
      >
        {codeExpanded ? '▴ Hide Full Code' : '▾ View Full Code'}
      </button>
      {codeExpanded && <pre className="code-block">{fix.script}</pre>}

      {!result && (
        <>
          <label className="restore-checkbox">
            <input
              type="checkbox"
              checked={restorePoint}
              onChange={(e) => setRestorePoint(e.target.checked)}
              disabled={running}
            />
            Create restore point before this fix
          </label>

          <div className="fix-actions">
            <button className="btn primary" onClick={approve} disabled={running}>
              {running ? (
                <>
                  <span className="spinner" /> Running…
                </>
              ) : (
                '✓ Approve'
              )}
            </button>
            <button
              className="btn danger-ghost"
              onClick={() => setDenied(true)}
              disabled={running}
            >
              ✗ Deny
            </button>
            <button
              className="btn ghost"
              onClick={() => setShowDetails((s) => !s)}
              disabled={running}
            >
              Ask for Details
            </button>
          </div>
        </>
      )}

      {result && (
        <div className="fix-result">
          <div className={`result-line ${result.status === 'Success' ? 'ok' : 'fail'}`}>
            {result.status === 'Success'
              ? '✓ Success'
              : `✗ Failed: ${result.errorMessage || 'see output'}`}{' '}
            <span className="muted">(exit code {result.exitCode})</span>
          </div>
          {result.restorePointCreated && (
            <div className="result-line muted">
              🛟 Restore point created —{' '}
              <button className="link-btn" onClick={openRestore}>
                undo this fix via System Restore
              </button>
            </div>
          )}
          {(result.beforeState || result.afterState) && (
            <div className="result-line muted">
              {result.beforeState && <>Before: {result.beforeState} </>}
              {result.afterState && <>→ After: {result.afterState}</>}
            </div>
          )}
          {result.output && (
            <>
              <button
                className="btn ghost sm code-toggle"
                onClick={() => setOutputExpanded((e) => !e)}
              >
                {outputExpanded ? '▴ Hide Output' : '▾ Show Output'}
              </button>
              {outputExpanded && <pre className="code-block">{result.output}</pre>}
            </>
          )}
        </div>
      )}
    </div>
  );
}
